/**
 * Wokwi Elements artwork, ported to React.
 *
 * Source: https://github.com/wokwi/wokwi-elements (MIT). The upstream parts are
 * Lit web components that each render a self-contained <svg>; a custom element
 * cannot be placed inside our scene's <svg> without a foreignObject, and inside
 * one it would keep its own shadow DOM — out of reach of the dim, highlight and
 * ghost states the canvas paints parts with. So the drawings are carried over
 * as plain React <g> fragments instead: same geometry, same pin positions, but
 * they compose with the rest of the scene like anything else we draw.
 *
 * Every `id` is prefixed, because several parts share one document here and two
 * <defs> called `grad1` would otherwise resolve to whichever rendered last.
 *
 * Generated by scripts/port-wokwi.py — do not edit by hand.
 */

import { resistorBands } from "./helpers";

/** Axial resistor — 15.645 x 3 in millimetres. Origin is the top-left of the left lead. */
export function ResistorArtwork({ ohms }: { ohms: number }) {
  const [band1Color, band2Color, band3Color] = resistorBands(ohms);
  return (
    <g>
      <defs>
        <linearGradient
          id="res-a"
          x2="0"
          y1="22.332"
          y2="38.348"
          gradientTransform="matrix(.14479 0 0 .14479 -23.155 -4.0573)"
          gradientUnits="userSpaceOnUse"
          spreadMethod="reflect"
        >
          <stop stopColor="#323232" offset="0" />
          <stop stopColor="#fff" stopOpacity=".42268" offset="1" />
        </linearGradient>
      </defs>
      <rect y="1.1759" width="15.558" height=".63826" fill="#aaa" />
      <g strokeWidth=".14479" fill="#d5b597">
        <path
          id="res-body"
          d="m4.6918 0c-1.0586 0-1.9185 0.67468-1.9185 1.5022 0 0.82756 0.85995 1.4978 1.9185 1.4978 0.4241 0 0.81356-0.11167 1.1312-0.29411h4.0949c0.31802 0.18313 0.71075 0.29411 1.1357 0.29411 1.0586 0 1.9185-0.67015 1.9185-1.4978 0-0.8276-0.85995-1.5022-1.9185-1.5022-0.42499 0-0.81773 0.11098-1.1357 0.29411h-4.0949c-0.31765-0.18244-0.7071-0.29411-1.1312-0.29411z"
        />
        <use xlinkHref="#res-body" fill="url(#res-a)" opacity=".44886" />
        <rect x="4" y="0" width="1" height="3" fill={band1Color} clipPath="url(#res-g)" />
        <path d="m6 0.29411v2.4117h0.96v-2.4117z" fill={band2Color} />
        <path d="m7.8 0.29411v2.4117h0.96v-2.4117z" fill={band3Color} />
        <rect x="10.69" y="0" width="1" height="3" fill="#F1D863" clipPath="url(#res-g)" />
        <clipPath id="res-g">
          <use xlinkHref="#res-body" />
        </clipPath>
      </g>
    </g>
  );
}
