/**
 * Wokwi Elements artwork, ported to React.
 *
 * Source: https://github.com/wokwi/wokwi-elements (MIT). The upstream parts are
 * Lit web components that each render a self-contained <svg>; a custom element
 * cannot be placed inside our scene's <svg> without a foreignObject, and inside
 * one it would keep its own shadow DOM — out of reach of the dim, highlight and
 * ghost states the canvas paints parts with. So the drawings are carried over
 * as plain React <g> fragments instead: same geometry, same pin positions, but
 * they compose with the rest of the scene like anything else we draw.
 *
 * Every `id` is prefixed, because several parts share one document here and two
 * <defs> called `grad1` would otherwise resolve to whichever rendered last.
 *
 * Generated by scripts/port-wokwi.py — do not edit by hand.
 */

import { hornPath, type HornType } from "./helpers";

/** SG90 micro servo — 170.08 x 119.55 in CSS pixels. Origin is the top-left of the lead ends, left of the case. */
export function ServoArtwork({ angle = 0, hornColor = "#ccc", horn = "single" }: { angle?: number; hornColor?: string; horn?: HornType }) {
  return (
    <g>
      <defs>
        <g id="servo-pin">
          <rect x="0" y="-1.91" width="3.72" height="3.71" />
          <path d="m2.026 -1.91h13.532l-13.425 0.51865z" />
          <path d="m2.026 1.80h13.532l-13.425-0.50702z" />
          <rect fill="#ccc" x="0.33" y="-1.23" width="3.04" height="2.46" rx=".15" />
        </g>
      </defs>
      <g strokeWidth="2.7" fill="none">
        <path
          stroke="#b44200"
          d="m 83.32,56.6 c0,0 -32.99,0.96 -43.32,0 -6.20,-0.58 -10.60,-6.20 -14.87,-6.31"
        />
        <path stroke="#ff2300" d="m83.326 59.6h-62.971" />
        <path
          stroke="#f47b00"
          d="m 83.32,62.6 c0,0 -32.60,-0.61 -43.33,-0.15 -6.87,0.29 -12.01,6.82 -14.77,6.73"
        />
      </g>
      <rect fill="#666" y="45.5" width="25.71" height="28" rx="1.14" />
      <use xlinkHref="#servo-pin" x="4.7" y="50.06" />
      <use xlinkHref="#servo-pin" x="4.7" y="59.66" />
      <use xlinkHref="#servo-pin" x="4.7" y="69.26" />
      <path
        fill="#4d4d4d"
        d="m163.92 66.867a7.09 7.09 0 1 1 5.8145-11.136 0.18 0.18 0 0 0 0.33-0.10234v-14.346h-17.664v36.98h17.676v-14.346a0.18 0.18 0 0 0-0.333-0.107 7.08 7.08 0 0 1-5.83 3.06z"
      />
      <path
        fill="#4d4d4d"
        d="m55.068 66.75a7.09 7.09 0 1 0-5.8261-11.136 0.18 0.18 0 0 1-0.33-0.10234v-14.346h17.676v36.98h-17.676v-14.346a0.18 0.18 0 0 1 0.333-0.107 7.08 7.08 0 0 0 5.83 3.06z"
      />
      <rect fill="#666" x="64.255" y="37.911" width="90.241" height="43.725" rx="5.3331" />
      <path fill="gray" d="m110.07 50.005h-14.42v19.537h14.42a9.7684 9.7684 0 0 0 0-19.537z" />
      <circle fill="#999" cx="91.467" cy="59.773" r="18.606" />
      <path
        fill={hornColor}
        transform={`translate(91.467 59.773) rotate(${angle ?? 0}) translate(-91.467 -59.773)`}
        d={hornPath(horn)}
      />
      <circle fill="gray" cx="91.467" cy="59.773" r="8.3729" />
      <circle fill="#ccc" cx="91.467" cy="59.773" r="6.2494" />
      <path
        fill="#666"
        d="m94.911 62.543-2.3839-2.4165a0.42562 0.42562 0 0 1 0-0.60471l2.4281-2.3863a0.64657 0.64657 0 0 0 0.06512-0.8652 0.62797 0.62797 0 0 0-0.93032-0.05117l-2.4351 2.4049a0.4326 0.4326 0 0 1-0.60703 0l-2.3863-2.4165a0.6489 0.6489 0 0 0-0.8652-0.06512 0.63262 0.63262 0 0 0-0.05117 0.93032l2.4049 2.4328a0.42795 0.42795 0 0 1 0 0.60703l-2.4142 2.3863a0.65122 0.65122 0 0 0-0.06745 0.8652 0.63029 0.63029 0 0 0 0.93032 0.05117l2.4351-2.4049a0.42562 0.42562 0 0 1 0.60471 0l2.3863 2.4398a0.63262 0.63262 0 0 0 0.93032-0.04186 0.64657 0.64657 0 0 0-0.04419-0.8652z"
      />
    </g>
  );
}
